- name: make sure ~/.ssh exists
  file:
    path: ~/.ssh
    state: directory

- name: set authorized_keys
  copy:
    src: authorized_keys
    dest: ~/.ssh/authorized_keys

- name: install ssh config
  copy:
    src: ssh_config
    dest: ~/.ssh/config
