- name: make sure ~/.ssh exists
  tags: [ssh]
  become: false
  file:
    path: ~/.ssh
    state: directory

- name: set authorized_keys
  tags: [ssh]
  become: false
  copy:
    src: authorized_keys
    dest: ~/.ssh/authorized_keys

- name: install ssh config
  tags: [ssh]
  become: false
  copy:
    src: ssh_config
    dest: ~/.ssh/config
