- name: make sure ~/.ssh exists
  file: >
    path=~japsu/.ssh
    state=directory
    mode=0700 owner=japsu

- name: set authorized_keys
  copy: >
    src=authorized_keys
    dest=~japsu/.ssh/authorized_keys mode=0600 owner=japsu
