---
- hosts: shells
  gather_facts: no
  roles:
    - role: server
      tags: [server]
    - role: user
      tags: [user]
    - role: shell
      tags: [shell]
    - role: ufw
      tags: [ufw]

- hosts: laptops
  gather_facts: no
  roles:
    - role: osx
      tags: [osx]
    - role: shell
      tags: [shell]

- hosts: helios
  gather_facts: no
  roles:
    - role: nginx
      tags: [nginx]
    - role: redirect
      tags: [redirect]
      redirect_server_name: helios.japsu.fi
      redirect_target: https://github.com/japsu
      redirect_ssl: false
      redirect_default: true
    - role: letsencrypt
      tags: [letsencrypt]
