---
- hosts: foreign-shells
  gather_facts: no
  roles:
    - shell

- hosts: own-shells
  gather_facts: no
  roles:
    - user
    - shell
    - irkki
    - ufw

- hosts: laptops
  gather_facts: no
  roles:
    - osx
    - shell
    - ruby
