---
- hosts: foreign-shells
  gather_facts: no
  roles:
    - role: shell
      tags: [shell]

- hosts: own-shells
  gather_facts: no
  roles:
    - role: server
      tags: [server]
    - role: user
      tags: [user]
    - role: shell
      tags: [shell]
    - role: ufw
      tags: [ufw]

- hosts: laptops
  gather_facts: no
  roles:
    - role: osx
      tags: [osx]
    - role: shell
      tags: [shell]
