- name: install ufw
  become: true
  apt: package=ufw state=installed

# - name: allow ssh through ufw
#   become: true
#   ufw: rule=allow port=22 proto=tcp

# - name: enable ufw
#   become: true
#   ufw: state=enabled policy=reject
