- name: install some packages
  apt: name={{ item }} state=installed
  with_items:
    - acl
    - apt-transport-https
    - build-essential
    - ca-certificates
    - curl
    - git
    - htop
    - man-db
    - ntp
    - python-apt
    - python-pip
    - python-dev
    - rsync
    - screen
    - vim
    - wget
    - whois

- name: allow mosh through firewall
  ufw: rule=allow port={{ item }} proto=udp
  with_items:
    - 60000
    - 60001
    - 60002
