- name: tap some homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/versions
    - homebrew/dupes
    - homebrew/versions

- name: install software via brew cask
  homebrew_cask: name={{ item }} install_options="force"
  with_items:
    - adobe-creative-cloud
    - bettertouchtool
    - chefdk
    - divvy
    - dockertoolbox
    - google-chrome
    - iterm2-beta
    - karabiner
    - microsoft-office
    - numi
    - paw
    - sonos
    - spotify
    - sublime-text
    - ubar
    - ukelele
    # - xquartz

    # order matters
    - virtualbox
    - vagrant

    # these are installed from app store instead
    # - dash
    # - slack


- name: install software via brew
  homebrew: name={{ item }}
  with_items:
    - ansible
    - bash-completion
    - git
    - gnupg2
    - lftp
    - mosh
    - nodejs
    - openssh
    - postgresql
    - pwgen
    - wine
