- name: tap some homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/versions
    - homebrew/dupes
    - homebrew/versions

- name: install software via brew cask
  homebrew_cask: name={{ item }}
  with_items:
    - adobe-creative-cloud
    - bettertouchtool
    # - dash # appstore
    - divvy
    - google-chrome
    - iterm2-beta
    - karabiner
    - microsoft-office
    - paw
    - slack
    - sublime-text3
    - ubar
    - ukelele
    - xquartz

- name: install software via brew
  homebrew: name={{ item }}
  with_items:
    - ansible
    - git
    - nodejs
    - openssh
    - mosh
    - bash-completion
    - wine
