- name: tap some homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/versions
    - homebrew/dupes
    - homebrew/versions

- name: install software via brew
  homebrew: name={{ item }}
  with_items:
    - ansible
    - git
    - nodejs
    - openssh

- name: install software via brew cask
  homebrew_cask: name={{ item }}
  with_items:
    - bettertouchtool
    - divvy
    - google-chrome
    - iterm2-beta
    - karabiner
    - sublime-text3
    - ukelele
    - dash
    - paw