- name: tap some homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/versions
    - homebrew/dupes
    - homebrew/versions

- name: install software via brew cask
  homebrew_cask: name={{ item }}
  with_items:
    - adobe-creative-cloud
    - bettertouchtool
    - chefdk
    - divvy
    - google-chrome
    - iterm2-beta
    - karabiner
    - microsoft-office
    - numi
    - paw
    - slack
    - sonos
    - spotify
    - sublime-text3
    - ubar
    - ukelele
    - xquartz

    # order matters
    - virtualbox
    - vagrant

    # these are installed from app store instead
    # - dash


- name: install software via brew
  homebrew: name={{ item }}
  with_items:
    - ansible
    - bash-completion
    - git
    - mosh
    - nodejs
    - openssh
    - postgresql
    - pwgen
    - wine
