- name: create sublime settings dir
  file: path="~/Library/Application Support/Sublime Text 3/Packages/User/" state=directory owner=japsu group=staff mode=0755

- name: install sublime text config
  copy: src=Preferences.sublime-settings dest="~/Library/Application Support/Sublime Text 3/Packages/User/" owner=japsu group=staff mode=0644
